version: '3.6'

services:
  ecdcservice:
    build: ./services/ecdc
    restart: always
    container_name: ecdcservice
    environment:
      TARANTOOL_USER_NAME: 'covid19_admin'
      TARANTOOL_USER_PASSWORD: 'noway'
    ports:
      - '3301:3301'
    networks:
      - quarantine
    healthcheck:
      disable: true
  mainweb:
    build: ./web
    restart: always
    container_name: mainweb
    ports:
      - '80:80'
    networks:
      - quarantine
    healthcheck:
      disable: true
    depends_on:
      - ecdcservice

networks:
  quarantine: