---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by uretgec.
--- DateTime: 19.04.2020 19:13
---

local model= {}
model['country'] = {}
model['country']['uid'] = nil
model['country']['iso2'] = nil
model['country']['iso3'] = nil
model['country']['code3'] = nil
model['country']['fibs'] = nil
model['country']['admin2'] = nil
model['country']['province_state'] = nil
model['country']['country_region'] = nil
model['country']['lat'] = nil
model['country']['long'] = nil
model['country']['combined_key'] = nil
model['country']['population'] = nil
model['stats'] = {}
model['stats']['confirmed'] = nil
model['stats']['deaths'] = nil
model['stats']['recovered'] = nil

return model