---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by uretgec.
--- DateTime: 19.04.2020 21:22
---
--- TODO:
--- external config.yaml file added
--- user defined functions added
---
local console = require('console')

box.cfg{
    listen='localhost:3301',
    wal_dir_rescan_delay=10,
    log_level=7,
    force_recovery=true
}

covid19_ecdc_space = box.space.covid19_ecdc_space
if not covid19_ecdc_space then
    box.schema.sequence.create('covid19_ecdc_sequence',{ if_not_exists=true })
    covid19_ecdc_space = box.schema.space.create('covid19_ecdc_space', { if_not_exists=true })
--[[    covid19_ecdc_space:format({
        {name='1', type='any'},
        {name='2', type='integer'},
        {name='3', type='string'},
        {name='4', type='unsigned'},
        {name='5', type='unsigned'},
        {name='6', type='string'},
        {name='7', type='string'},
        {name='8', type='string'},
        {name='9', type='string'},
        {name='10', type='unsigned'},
    })]]
    covid19_ecdc_space:create_index('primary', {sequence='covid19_ecdc_sequence', if_not_exists=true, parts= { {field=1, type='unsigned'} }})
    covid19_ecdc_space:create_index('secondary', {unique=false, type='tree', if_not_exists=true, parts={ {field=7, type='string'}, {field=2, type='integer'} }})

    box.schema.user.create('covid19_ecdc_admin', {password = 'ecdc', if_not_exists = true})
    box.schema.user.grant('covid19_ecdc_admin','read,write,execute,create,drop','universe')
else
--[[    covid19_ecdc_space:drop()]]
end

--[[
console.start()]]
