---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by uretgec.
--- DateTime: 29.04.2020 00:02
---

local ecdc = {}
function ecdc.api()
    local api = {}
    function api.findBy(query)
        -- country, date, offset, limit, order
        return { result='deneme' }
        -- return covid19_ecdc_space.index.secondary:select({'TR'})
    end

    function api.reset()
        covid19_ecdc_space:truncate()
        if covid19_ecdc_space:len() > 0 then
            return false
        end

        box.sequence.covid19_ecdc_sequence:reset()
        return true
    end

    return api
end

return ecdc