---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by uretgec.
--- DateTime: 19.04.2020 21:22
---
--- TODO:
--- external config.yaml file added
--- user defined functions added
---

--[[local conf = require('config.default')]]
local ecdc = require('api')

box.cfg{
    listen=3301,
    wal_dir_rescan_delay=10,
    log_level=7,
    force_recovery=true
}

covid19_ecdc_space = box.space.covid19_ecdc_space
if not covid19_ecdc_space then
    box.schema.sequence.create('covid19_ecdc_sequence',{ if_not_exists=true })
    covid19_ecdc_space = box.schema.space.create('covid19_ecdc_space', { if_not_exists=true })

    covid19_ecdc_space:create_index('primary', {sequence='covid19_ecdc_sequence', if_not_exists=true, parts= { {field=1, type='unsigned'} }})
    covid19_ecdc_space:create_index('secondary', {unique=false, type='tree', if_not_exists=true, parts={ {field=7, type='string'}, {field=2, type='integer'} }})

    -- box.schema.user.create('covid19_admin', {password = 'noway', if_not_exists = true})
    -- box.schema.user.grant('covid19_admin','read,write,execute,create,drop','universe')

    box.schema.user.grant('guest','read,write,execute','universe')
end

covid19 = ecdc.api()

function findMy(req, query)
    -- country, date, offset, limit, order
    return { 'ok' }
    -- return covid19_ecdc_space.index.secondary:select({'TR'})
end