---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by uretgec.
--- DateTime: 26.04.2020 19:56
---

return {
    spaces = {
        ecdc = {
            name = 'covid19_ecdc_space'
        }
    }
}