---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by uretgec.
--- DateTime: 19.04.2020 13:59
---

box.cfg{listen=3301}
covid19Space = box.space.covid19Space
if not covid19Space then
    box.schema.sequence.create('covid19Sequence',{ if_not_exists = true })
    covid19Space = box.schema.space.create('covid19Space', { if_not_exists = true })
    covid19Space:create_index('primary', {sequence='covid19Sequence', if_not_exists = true})
    covid19Space:create_index('secondary', {unique = false, if_not_exists = true, parts={ {field = 9, type = 'string'}, {field = 2, type = 'integer'} }})

    box.schema.user.create('covid19User', {password = 'imhere', if_not_exists = true})
    box.schema.user.grant('covid19User','read,write,execute,create,drop','universe')
end

--[[local tarantool= require('tarantool')]]
--[[local fio= require('fio')
local csv= require('csv')
local errno = require('errno')
local console = require('console')

local f = fio.open('covid-19.txt', {'O_RDONLY'})
local opts = {skip_head_lines = 1, delimiter = ',' }
]]--[[local csvFile = csv.load(f, opts)]]--[[

if not f then
    error("Failed to open file: "..errno.strerror())
end

for i, tup in csv.iterate(f, opts) do
    covid19Space:insert({null, os.time({year = tup[4], month = tup[3], day = tup[2]}), tup[2], tup[3], tup[4], tup[5], tup[6], tup[7], tup[8], tup[9], tup[10]})
    ]]--[[ print(i, tup[1], os.time({year = tup[4], month = tup[3], day = tup[2]})) ]]--[[
end

f:close()]]

--[[console.start()]]
